const router=require("express").Router();
const controller=require("./demo-banks.controller");
const schemas=require("./demo-banks.validation");
const validate=require("../../middleware/validate.middleware");
const {resolveTenantMiddleware}=require("../../middleware/tenant.middleware");
const {authenticate}=require("../../middleware/auth.middleware");
router.use(resolveTenantMiddleware);
router.use(authenticate);
router.get("/",controller.list);
router.post("/resolve",validate(schemas.resolveSchema),controller.resolve);
module.exports=router;
