export type ClientTransaction = {
  id: string;
  tenant_id: string;
  account_id: string;
  transfer_id: string | null;
  entry_type: "credit" | "debit";
  amount: string | number;
  balance_after: string | number;
  description: string | null;
  created_at: string;
  account_number: string;
  account_name: string;
  currency: string;
  reference: string | null;
  status: string | null;
  source_account_id: string | null;
  destination_account_id: string | null;
  destination_account_number: string | null;
  transfer_type?: "internal" | "external";
  transfer_destination_account_name?: string | null;
  destination_bank_name?: string | null;
  destination_bank_code?: string | null;
  settlement_mode?: "internal" | "simulation" | "provider";
  is_simulated?: boolean | number;
  source_account_name: string | null;
  source_account_number: string | null;
  destination_account_name: string | null;
  destination_account_number_resolved: string | null;
};
